
import { CaffeineBeverage } from './types';

// Sample catalog of caffeine beverages
export const BEVERAGE_CATALOG: CaffeineBeverage[] = [
  {
    id: "coffee-1",
    name: "Espresso",
    category: "coffee",
    caffeine: 63,
    servingSize: "1 oz shot",
    servingSizeOz: 1,
  },
  {
    id: "coffee-2",
    name: "Brewed Coffee",
    category: "coffee",
    caffeine: 95,
    servingSize: "8 oz cup",
    servingSizeOz: 8,
  },
  {
    id: "coffee-3",
    name: "Cold Brew",
    category: "coffee",
    caffeine: 120,
    servingSize: "12 oz cup",
    servingSizeOz: 12,
  },
  {
    id: "coffee-4",
    name: "Starbucks Coffee",
    category: "coffee",
    caffeine: 155,
    servingSize: "8 oz cup",
    servingSizeOz: 8,
  },
  {
    id: "coffee-5",
    name: "Dunkin' Donuts Coffee",
    category: "coffee",
    caffeine: 112,
    servingSize: "10 oz cup",
    servingSizeOz: 10,
  },
  {
    id: "coffee-6",
    name: "Starbucks Caffè Latte",
    category: "coffee",
    caffeine: 75,
    servingSize: "12 oz cup",
    servingSizeOz: 12,
  },
  {
    id: "coffee-7",
    name: "Starbucks Nitro Cold Brew",
    category: "coffee",
    caffeine: 280,
    servingSize: "16 oz cup",
    servingSizeOz: 16,
  },
  {
    id: "bottled-coffee-1",
    name: "Starbucks Frappuccino",
    category: "coffee",
    caffeine: 110,
    servingSize: "13.7 oz bottle",
    servingSizeOz: 13.7,
  },
  {
    id: "bottled-coffee-2",
    name: "SToK Cold Brew",
    category: "coffee",
    caffeine: 185,
    servingSize: "13.7 oz bottle",
    servingSizeOz: 13.7,
  },
  {
    id: "tea-1",
    name: "Black Tea",
    category: "tea",
    caffeine: 47,
    servingSize: "8 oz cup",
    servingSizeOz: 8,
  },
  {
    id: "tea-2",
    name: "Green Tea",
    category: "tea",
    caffeine: 28,
    servingSize: "8 oz cup",
    servingSizeOz: 8,
  },
  {
    id: "tea-3",
    name: "Snapple Tea",
    category: "tea",
    caffeine: 42,
    servingSize: "16 oz bottle",
    servingSizeOz: 16,
  },
  {
    id: "tea-4",
    name: "Lipton Brisk Iced Tea",
    category: "tea",
    caffeine: 9,
    servingSize: "12 oz can",
    servingSizeOz: 12,
  },
  {
    id: "energy-1",
    name: "Red Bull",
    category: "energy",
    caffeine: 80,
    servingSize: "8.4 oz can",
    servingSizeOz: 8.4,
  },
  {
    id: "energy-2",
    name: "Monster Energy",
    category: "energy",
    caffeine: 160,
    servingSize: "16 oz can",
    servingSizeOz: 16,
  },
  {
    id: "energy-3",
    name: "5-Hour Energy",
    category: "energy",
    caffeine: 200,
    servingSize: "1.93 oz shot",
    servingSizeOz: 1.93,
  },
  {
    id: "energy-4",
    name: "Reign Total Body Fuel",
    category: "energy",
    caffeine: 300,
    servingSize: "16 oz can",
    servingSizeOz: 16,
  },
  {
    id: "energy-5",
    name: "Bang Energy",
    category: "energy",
    caffeine: 300,
    servingSize: "16 oz can",
    servingSizeOz: 16,
  },
  {
    id: "soda-1",
    name: "Coca-Cola",
    category: "soda",
    caffeine: 34,
    servingSize: "12 oz can",
    servingSizeOz: 12,
  },
  {
    id: "soda-2",
    name: "Diet Coke",
    category: "soda",
    caffeine: 46,
    servingSize: "12 oz can",
    servingSizeOz: 12,
  },
  {
    id: "soda-3",
    name: "Mountain Dew",
    category: "soda",
    caffeine: 55,
    servingSize: "12 oz can",
    servingSizeOz: 12,
  },
  {
    id: "soda-4",
    name: "Pepsi",
    category: "soda",
    caffeine: 38,
    servingSize: "12 oz can",
    servingSizeOz: 12,
  },
  {
    id: "soda-5",
    name: "Dr Pepper",
    category: "soda",
    caffeine: 41,
    servingSize: "12 oz can",
    servingSizeOz: 12,
  },
];
