// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://refutfwpwtubgstbnela.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlZnV0Zndwd3R1YmdzdGJuZWxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDMzMzgsImV4cCI6MjA1OTg3OTMzOH0.njTCmMOwsgPE66ttzgRDptBhnLrsHiQ3w3wukkOsRlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);